name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Build Docker Images for battery-management-service and battery-update-service
        run: |
          docker build -t battery-management-service ./cc
          docker build -t battery-update-service ./bu

      - name: Push Docker Images to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag battery-management-service ${{ secrets.DOCKER_USERNAME }}/battery-management-service:latest
          docker tag battery-update-service ${{ secrets.DOCKER_USERNAME }}/battery-update-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/battery-management-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/battery-update-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy with Docker Compose
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.USER }}@${{ secrets.HOST }} \
          "cd /path/to/the/project && docker-compose down && docker-compose pull && docker-compose up -d"
